spring.application.name=college-recommend-system

spring.datasource.url=jdbc:postgresql://localhost:5432/collegedb
spring.datasource.username=postgres
spring.datasource.password=07052021

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE CONFIGURATION
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

# =============================================
# Access token ? short lifetime (10?15 min)
# Refresh token ? long lifetime (7?30 days)
# ==============================================
# JWT Configuration

jwt.secret=8d2f4c6a7b91e0d3f5c6a1b9e2d7f4c8b0a9e3f1c7d6b2a4e8f5c1d9a7b3c6e2
jwt.access-expiration=900000
jwt.refresh-expiration=604800000


razorpay.key.id=rzp_test_SN8w1CRy6KFPz6
razorpay.key.secret=qa0Y6sGwtakh93r4Ptd2VsxK
razorpay.webhook.secret= i6@5@PgfHYvWnHB 


cloudinary.cloud-name=dd3g7mlkl
cloudinary.api-key=139563786914658
cloudinary.api-secret=3DRX2de8cr59CWFxagHNRjaD2iI
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB